# Generated by Django 5.2.6 on 2025-12-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(through='barber_app.BarberService', to='barber_app.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='fa-cut', help_text='Например: fa-scissors, fa-beard, fa-shower, fa-hat-cowboy и т.д.', max_length=50, verbose_name='Иконка (Font Awesome)'),
        ),
    ]
