# Generated by Django 5.2.6 on 2025-12-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0002_barber_services_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(choices=[('fa-cut', 'Ножницы'), ('fa-scissors', 'Ножницы 2'), ('fa-beard', 'Борода'), ('fa-user', 'Пользователь'), ('fa-user-tie', 'Деловой'), ('fa-shower', 'Душ'), ('fa-spa', 'СПА'), ('fa-wind', 'Укладка'), ('fa-hat-cowboy', 'Шляпа'), ('fa-heart', 'Подарок'), ('fa-star', 'Премиум'), ('fa-tools', 'Комплекс'), ('fa-pen-fancy', 'Стиль'), ('fa-gem', 'Элит'), ('fa-shield-alt', 'Гарантия'), ('fa-clock', 'Время')], default='fa-cut', help_text='Выберите иконку из списка', max_length=50, verbose_name='Иконка (Font Awesome)'),
        ),
    ]
